name: Build Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip project
        run: unzip iptv_terry.zip
      
      - name: List files
        run: ls -R
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      
      - name: Get dependencies
        run: cd iptv_terry && flutter pub get
        
      - name: Build APK Debug
        run: cd iptv_terry && flutter build apk --debug --split-per-abi
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: iptv_terry/build/app/outputs/flutter-apk/*.apk
